baseURL: "https://jadevandorth.github.io"           # CHANGE TO OWN DOMAIN
title: Jade Suiyue Yue van Dorth   		    # SITE TITLE - SHOWS IN BROWSER TAB & HEADER
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20					    # NUMBER OF POSTS PER PAGE

taxonomies:
    tag: tags

# ---------------------------
# MENU SETTINGS
# ---------------------------

menu:
    main:
        - name: About Me       		            # TEXT IN MENU
          url: about/                               # URL content/about.md should exist
          weight: 1                                 # ORDER OF APPEARANCE
        - name: Conferences
          url: conferences/
          weight: 2
        - name: Papers
          url: papers/
          weight: 3
        - name: Blog
          url: blog/
          weight: 4
        - name: Search
          url: search
          weight: 5

# ---------------------------
# SITE PARAMETERS
# ---------------------------

params:
    description: "This is the personal website of Jade Suiyue Yue van Dorth."

    author: Jade Suiyue Yue van Dorth

    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    ShowToc: false
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true

  # ADD CUSTOM CSS FILES BELOW HERE, IF DESIRED
  customCSS:
    - css/extended/theme-vars-override.css

  # ---------------------------
  # HOMEPAGE PROFILE MODE
  # ---------------------------

    profileMode:
          enabled: true
          title: Jade Suiyue Yue van Dorth (MSc)       # TITLE ON HOMEPAGE

          subtitle: "Hello there! I am a PhD-candidate in human-AI communication at The University of Amsterdam. I love exploring emerging technologies and reflecting on how they shape the experiences and futures of young people today. I have previously worked as a research assistant on projects focused on human-robot interactions and addressing the needs of long COVID patients. I earned both my BSc and MSc (research) degrees in Communication Science at the University of Amsterdam." 

          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
           - name: About me
             url: about/
           - name: Conferences
             url: conferences/
           - name: Papers
             url: papers/
           - name: Blog
             url: blog/

  # ---------------------------
  # SOCIAL ICONS (BOTTOM OF PROFILE)
  # ---------------------------

    socialIcons:
        - name: CV
          url: cvjade.pdf
        - name: Location
          url: https://ascor.uva.nl/contact/contact.html
        - name: ORCID
          url: https://orcid.org/0009-0001-5016-0200
        - name: LinkedIn
          url: https://www.linkedin.com/in/jade-van-dorth-608b30213/
        - name: GitHub
          url: https://github.com/jadevandorth

# ---------------------------
# APPEARANCE
# ---------------------------

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jade Suiyue Yue van Dorth"
      icon: favicon.ico
      iconHeight: 18

  # ---------------------------
  # MARKUP OPTIONS
  # ---------------------------

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2