baseURL: "https://jadevandorth.github.io"           # CHANGE TO YOUR OWN DOMAIN
title: Jade Suiyue Yue van Dorth   		    # SITE TITLE - SHOWS IN BROWSER TAB & HEADER
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20					    # NUMBER OF POSTS PER PAGE

taxonomies:
    tag: tags

# ---------------------------
# MENU SETTINGS
# ---------------------------

menu:
    main:
        - name: About Me       		            # TEXT IN MENU
          url: about/                               # URL content/about.md should exist
          weight: 1                                 # ORDER OF APPEARANCE
        - name: Papers
          url: papers/
          weight: 2
        - name: Blog
          url: blog/
          weight: 3
        - name: Search
          url: search/
	  weight: 4

# ---------------------------
# SITE PARAMETERS
# ---------------------------

params:
    description: "This is the personal site of Jade Suiyue Yue van Dorth. You can learn more About Me, explore my Papers, read updates on my Blog, and use the Search function to find specific content."

    author: Jade Suiyue Yue van Dorth

    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"] # THIS NEEDS TO BE CHANGED? 
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true

  # ---------------------------
  # HOMEPAGE PROFILE MODE
  # ---------------------------

    profileMode:
          enabled: true
          title: Jade Suiyue Yue van Dorth (MSc)       # LARGE TITLE ON HOMEPAGE

          subtitle: "I am a Ph.D. student in human-AI communication at The University of Amsterdam. I love exploring emerging technologies and reflecting on how they shape the experiences and futures of young people today. I am passionate about bridging the gap between AI research and real-world impacts, especially for the next generation." 

          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
        - name: About me
        url: about/
        - name: Papers
        url: papers/
        - name: Blog
        url: blog/
        - name: Search
        url: search/

  # ---------------------------
  # SOCIAL ICONS (BOTTOM OF PROFILE)
  # REMOVE IF NOT WANTED
  # ---------------------------

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: GitHub
          url: https://github.com/jadevandorth

# ---------------------------
# APPEARANCE
# ---------------------------

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jade Suiyue Yue van Dorth"
      icon: favicon.ico
      iconHeight: 18

  # ---------------------------
  # MARKUP OPTIONS
  # ---------------------------

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2